#!/usr/bin/env python3
"""Paper template for a conjecture settled by the COMPLETE annihilation test.

House style. Used where the conjectured operator is not a left multiple of the one
the entry states, so the divisibility argument does not apply and the residual after
division has to be shown to vanish on the sequence itself.
"""
TEMPLATE = r"""\documentclass[11pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsthm}
\usepackage[margin=1in]{geometry}
\usepackage[colorlinks=true,linkcolor=blue,urlcolor=blue]{hyperref}
\theoremstyle{plain}
\newtheorem{theorem}{Theorem}
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{corollary}[theorem]{Corollary}
\theoremstyle{definition}
\newtheorem{remark}[theorem]{Remark}
\title{A proof of the conjectured recurrence for OEIS %(ANUM)s}
\author{Adrian Perez Fontelles\\ \small Independent researcher}
\date{26 August 2026}
\begin{document}
\maketitle

\begin{abstract}
OEIS %(ANUM)s carries a conjectured linear recurrence with polynomial coefficients, of
order %(ORDERC)d. The entry separately states a recurrence of order %(ORDERP)d that is not
labelled a conjecture. We prove that the first is a consequence of the second, so the
conjecture holds. The argument is a division in the Ore algebra
$\mathbb{Q}(n)[N]$, where $N$ is the shift $Nf(n)=f(n+1)$: writing $C$ and $P$ for the two
recurrences read as operators, we exhibit $Q$ with $C=QP$, whence
$C(a)=Q(P(a))=Q(0)=0$. No generating function is used. The division is exact
rational-function arithmetic, and the finitely many $n$ excluded by denominators of $Q$
are computed rather than ignored.
\end{abstract}

\noindent\small 2020 Mathematics Subject Classification. 11B37, 12H10, 33F10.\normalsize

\section{The sequence and the two recurrences}

OEIS %(ANUM)s is ``%(NAME)s''. It has offset $%(OFFSET)d$ and begins
\[
%(FIRSTTERMS)s
\]
The entry carries the following comment, still recorded as a conjecture:
\begin{quote}\small
%(CONJ)s
\end{quote}
As of the ``Last modified'' line on the live entry (%(TIME)s, revision %(REV)s) it is still
a conjecture, and no proof appears among the entry's links, formulas or programs.

The same entry also states, \emph{not} as a conjecture:
\begin{quote}\small
%(PROVEN)s
\end{quote}
This second relation is what the argument below rests on; it is taken as given, exactly as
a posted generating function would be. It was checked against the entry's own DATA before
being used, and holds on every published term it reaches.

\section{Recurrences as operators, and what division really proves}

Write a recurrence as an element of the Ore algebra $\mathcal{A}=\mathbb{Q}(n)[N]$, where
$N$ is the shift $Nf(n)=f(n+1)$ and multiplication obeys $N\,q(n)=q(n+1)\,N$. Let $C$ be
the conjectured operator and $P$ the operator the entry states as fact, so $P(a)=0$.

The obvious test is whether $C$ is a left multiple of $P$. If $C=QP$ then
$C(a)=Q(P(a))=Q(0)=0$ and the conjecture follows. But the converse fails, and not as a
technicality: $C(a)=0$ requires only that $C$ lie in the left ideal of \emph{all} operators
annihilating $a$, which is generated by the minimal one, and $P$ is in general a proper
multiple of that. A conjecture can be true with $C$ not a left multiple of $P$, and
%(ANUM)s is such a case.

The complete test is short. Divide on the right,
\[
C \;=\; QP + R, \qquad \operatorname{ord}(R) < \operatorname{ord}(P) = r ,
\]
so that
\[
C(a) \;=\; Q\bigl(P(a)\bigr) + R(a) \;=\; R(a),
\]
and the question becomes whether $R(a)$ vanishes, where $R$ has order below $r$.

\begin{lemma}\label{lem:module}
Write $S(n)=R(a)(n)=\sum_{i<r}s_{i}(n)\,a(n+i)$. Then $S,\,NS,\,\dots,\,N^{r}S$ all lie in
the $\mathbb{Q}(n)$-span of $a(n),\dots,a(n+r-1)$, and are therefore linearly dependent
over $\mathbb{Q}(n)$. Any such dependence is an operator $T$ of order $d\le r$ with
$T(S)=0$.
\end{lemma}

\begin{proof}
Shifting $S$ replaces each $a(n+i)$ by $a(n+i+1)$; the only term leaving the span is
$a(n+r)$, and $P(a)=0$ expresses it as a $\mathbb{Q}(n)$-combination of
$a(n),\dots,a(n+r-1)$, its coefficient being $-P_{j}/P_{r}$. So each shift stays inside an
$r$-dimensional space, and $r+1$ vectors in it are dependent.
\end{proof}

\begin{lemma}\label{lem:prop}
Let $T$ have order $d$ and leading coefficient with no zero at any integer $n\ge n_{0}$. If
$T(S)=0$ and $S(n_{0})=\dots=S(n_{0}+d-1)=0$, then $S(n)=0$ for every $n\ge n_{0}$.
\end{lemma}

\begin{proof}
Induction: the recurrence $T(S)=0$ determines $S(m+d)$ from the previous $d$ values
whenever the leading coefficient at $m$ is nonzero.
\end{proof}

So $C(a)=0$ is decided exactly: divide, compute $T$, evaluate $S$ at $d$ indices, and check
the leading coefficient. The case $R=0$ recovers the divisibility test as a special case.

\section{The computation for %(ANUM)s}

Dividing $C$ by $P$ on the right leaves quotient
\[
Q\;=\;%(QLATEX)s
\]
and remainder
\[
R\;=\;%(RLATEX)s ,
\]
which is not zero: the conjectured operator is genuinely not a left multiple of the stated
one, and the divisibility test alone would have refused this conjecture.

Carrying out Lemma~\ref{lem:module} gives an operator $T$ of order $%(TORDER)d$ with
$T(S)=0$, namely
\[
T\;=\;%(TLATEX)s .
\]
%(TPOLETEXT)s Evaluating $S(n)=R(a)(n)$ on the entry's own terms gives $0$ at the
$%(TORDER)d$ consecutive indices beginning $n=%(SFROM)d$, so by Lemma~\ref{lem:prop}
$S$ vanishes identically from there on, and $C(a)=0$.

\begin{theorem}
The conjectured recurrence
\[
%(RECLATEX)s \;=\;0
\]
holds for every $n\ge%(FIRSTN)d$.
\end{theorem}

\begin{proof}
$C(a)=R(a)=S$ by the division above, and $S$ vanishes from $n=%(SFROM)d$ onward by
Lemma~\ref{lem:prop}. The stated recurrence $P$ is asserted by the entry and was checked
against its published terms before use.
\end{proof}

\section{Verification}

Every number above is an output of a script written separately from this note, and three
independent checks were run.

First, the factorisation was not assumed but computed, and then confirmed by multiplying
back: $QP$ was expanded in $\mathcal{A}$ and its coefficients cancelled against those of
$C$ to zero, as rational functions of $n$.

Second, the relation the argument rests on was checked against the entry rather than
trusted: the stated recurrence was evaluated on the published terms in exact integer
arithmetic and holds on every one it reaches.

Third, the conjecture itself was evaluated the same way, directly and without reference to
either operator: for each $n$ in range the sum $\sum_{i}p_{i}(n)a(n-i)$ was formed from the
entry's own values and found to vanish, for all %(NVER)d values of $n$ from
$n=%(FIRSTN)d$ upward.

\begin{thebibliography}{9}
\bibitem{oeis} The OEIS Foundation, \emph{The On-Line Encyclopedia of Integer Sequences},
\url{https://oeis.org}, 2026. Sequence %(ANUM)s.
\bibitem{ore} O.~Ore, \emph{Theory of non-commutative polynomials}, Ann. of Math. 34
(1933), 480--508.
\bibitem{kp} M.~Kauers and P.~Paule, \emph{The Concrete Tetrahedron}, Springer, 2011,
Chapter 7.
\bibitem{bronstein} M.~Bronstein and M.~Petkov\v{s}ek, \emph{An introduction to
pseudo-linear algebra}, Theoret. Comput. Sci. 157 (1996), 3--33.
\end{thebibliography}
\end{document}
"""
