#!/usr/bin/env python3
"""A complete test for "does this operator annihilate this sequence?"

The Ore engine so far asked whether the conjectured operator C is a LEFT MULTIPLE of a
known annihilator L. If it is, C(a)=0 follows. But the converse is false, and that is not
a technicality: C(a)=0 only requires C to lie in the left ideal of ALL operators killing
a, which is generated by the minimal one, and L is generally a proper multiple of that.
So the old test refused true conjectures, and the refusals looked like mathematics.

The complete test is short. Right-divide, C = QL + R with order(R) < order(L) = r. Then

    C(a) = Q(L(a)) + R(a) = R(a),

so the question is whether R(a) vanishes, where R has order below r. Write

    S(n) = R(a)(n) = sum_{i<r} s_i(n) a(n+i).

Because a satisfies L, the shifts of S all live in the r-dimensional module spanned by
a(n),...,a(n+r-1) over Q(n): shifting once and reducing a(n+r) through L keeps you inside
it. So S, NS, ..., N^r S are r+1 vectors in an r-dimensional space and are linearly
dependent over Q(n). That dependency is an operator T of order d <= r with T(S)=0.

A sequence annihilated by T that vanishes at d consecutive indices, and whose leading
coefficient has no integer zero beyond them, is zero from there on -- the recurrence
propagates it forward. So S = 0 is decided by evaluating S at d points and checking the
leading coefficient, both exact.

This is strictly stronger than the divisibility test, and it never says yes where the old
one said yes wrongly: R = 0 is the special case that recovers it.
"""
import sympy as sp
import ore

n = sp.Symbol('n')


def reduce_right(C, L):
    """C = Q L + R with order(R) < order(L); returns (Q, R) as coefficient lists."""
    return ore.right_divide(C, L)


def _shift_vector(v, L):
    """N applied to sum_i v_i(n) a(n+i), reduced back into the module."""
    r = len(L) - 1
    lead = L[-1]
    w = [sp.Integer(0)] * r
    for i, c in enumerate(v):
        c1 = sp.cancel(c.subs(n, n + 1))
        if c1 == 0:
            continue
        if i + 1 < r:
            w[i + 1] = sp.cancel(w[i + 1] + c1)
        else:
            # a(n+r) = -sum_{j<r} (L_j/L_r) a(n+j)
            for j in range(r):
                w[j] = sp.cancel(w[j] - c1 * L[j] / lead)
    return w


def annihilator_of_residual(R, L):
    """An operator T with T(S) = 0, where S(n) = sum_i R_i(n) a(n+i). None if it fails."""
    r = len(L) - 1
    v = [sp.cancel(R[i]) if i < len(R) else sp.Integer(0) for i in range(r)]
    if all(c == 0 for c in v):
        return [sp.Integer(1)]                 # S is identically zero already
    vs = [v]
    for _ in range(r):
        vs.append(_shift_vector(vs[-1], L))
    # find the first linear dependency among vs[0..d] over Q(n)
    for d in range(1, len(vs)):
        M = sp.Matrix([[sp.cancel(vs[j][i]) for j in range(d + 1)] for i in range(r)])
        ns = M.nullspace()
        if ns:
            t = ns[0]
            coeffs = [sp.cancel(sp.together(t[j])) for j in range(d + 1)]
            den = sp.lcm([sp.denom(c) for c in coeffs]) if any(
                sp.denom(c) != 1 for c in coeffs) else sp.Integer(1)
            coeffs = [sp.expand(sp.cancel(c * den)) for c in coeffs]
            while len(coeffs) > 1 and coeffs[-1] == 0:
                coeffs.pop()
            return coeffs
    return None


def residual_values(R, seq, off, lo, count):
    """S(n) for n = lo .. lo+count-1, from the sequence's actual terms."""
    out = []
    for m in range(lo, lo + count):
        tot = sp.Integer(0)
        for i, c in enumerate(R):
            idx = m + i - off
            if idx < 0 or idx >= len(seq):
                return None
            tot += sp.nsimplify(sp.cancel(c).subs(n, m), rational=True) * seq[idx]
        if not sp.simplify(tot).is_number:
            return None
        out.append(sp.nsimplify(sp.simplify(tot), rational=True))
    return out


def vanishes(R, L, seq, off, start):
    """(True, T, first_n) if S is identically zero from some index on; else (False, ...).

    start is the first index at which L is asserted to annihilate the sequence.
    """
    if all(sp.cancel(c) == 0 for c in R):
        return True, [sp.Integer(1)], start, []
    T = annihilator_of_residual(R, L)
    if T is None:
        return False, None, None, []
    d = len(T) - 1
    if d == 0:
        # T_0(n) S(n) = 0 with T_0 not identically zero: S vanishes off T_0's zero set
        bad = _integer_roots(T[0])
        return True, T, start, bad
    bad = _integer_roots(T[-1])
    lo = start
    while lo in bad:
        lo += 1
    vals = residual_values(R, seq, off, lo, d)
    if vals is None:
        return False, T, None, bad
    if any(v != 0 for v in vals):
        return False, T, None, bad
    if any(b > lo for b in bad):
        return False, T, None, bad          # the propagation would break at that index
    return True, T, lo, bad


def _integer_roots(p):
    p = sp.expand(sp.cancel(sp.together(p)))
    if p == 0 or not p.free_symbols:
        return []
    try:
        return sorted({int(r) for r in sp.solve(sp.Eq(sp.numer(p), 0), n)
                       if r.is_Integer})
    except Exception:
        return []
