#!/usr/bin/env python3
"""The paper for a conjectured P-RECURSIVE recurrence settled from an algebraic g.f.

The theorem is an identity of FUNCTIONS, not a run of verified terms, and the paper has to say
so: the residual B(x) is an explicit element of an algebraic function field, and the claim
holds for every n > deg B because B is a polynomial of that degree, at every index at once.
"""
import sympy as sp

import localentry as LE
import phibuild
import unibuild

PRE, esc = phibuild.PRE, phibuild.esc
x = sp.Symbol('x')
n = sp.Symbol('n')


def build(h):
    a = h['anum']
    e = LE.get(a)
    d = [int(v) for v in e['data'].split(',') if v.strip()]
    ps = [sp.sympify(p) for p in h['ps']]
    r = h['order']
    A = sp.sympify(h['gf'])
    zero, degB, frm = h['zero'], h['degB'], h['from_n']
    head = ', '.join(str(v) for v in d[:8])
    rec = ' + '.join(rf'\left({sp.latex(p)}\right)a(n-{i})' if i else
                     rf'\left({sp.latex(p)}\right)a(n)' for i, p in enumerate(ps) if p != 0)
    if zero:
        concl = (r"Here $B$ is identically zero, so the recurrence holds for EVERY $n$ at "
                 r"which its indices are defined.")
        thm = r"for every $n\ge%d$." % r
    else:
        concl = (rf"Here $B$ is a polynomial of degree ${degB}$. A polynomial contributes only "
                 rf"to the coefficients of $x^k$ with $k\le{degB}$, so $b(n)=0$ for every "
                 rf"$n>{degB}$.")
        thm = r"for every $n>%d$." % degB
    return rf"""{PRE}
\title{{The conjectured P-recursive recurrence for OEIS {a}, proved}}
\author{{Adrian Perez Fontelles\\ \small Independent researcher}}
\date{{{unibuild.DATE}}}
\begin{{document}}
\maketitle

\begin{{abstract}}
OEIS {a} carries a conjectured recurrence of order ${r}$ whose coefficients are polynomials in
$n$ rather than constants. It is true, and it is decidable rather than empirical. The entry
states its generating function as a fact, and that function is algebraic; the conjecture then
becomes the vanishing of an explicit element of an algebraic function field, which is settled
symbolically. The result is an identity, not a run of verified terms: it holds at every index
at once.
\end{{abstract}}

\noindent\small 2020 Mathematics Subject Classification. 05A15, 33F10, 11B37.\normalsize

\section{{The conjecture}}

OEIS {a} is ``{esc(e['name'])}''. It has offset ${h['offset']}$ and begins
\[
{head},\ \dots
\]
The entry states, as a conjecture contributed by its author and never marked settled:
\begin{{quote}}\raggedright\small
{esc(h['line'])}
\end{{quote}}
As of the ``Last modified'' line on the live entry ({e['modified']}, revision {e['revision']})
this is still recorded as a conjecture, and nothing on the entry records it as proved.

\section{{The generating function}}

The entry gives, as a statement of fact and not as a conjecture,
\[
A(x)\;=\;{sp.latex(A)} .
\]
This is an algebraic function. Before it is used for anything it is checked against the entry's
own data: its Taylor coefficients reproduce every one of the ${h['nterms']}$ published terms
exactly, in exact arithmetic. That check is not a formality --- on A116388 the generating
function an entry states as fact does NOT generate the terms it publishes, and a proof built on
it would have been a proof from a false premise.

\section{{A P-recursive claim is the vanishing of one function}}

\begin{{lemma}}\label{{lem:theta}}
Let $\theta=x\,\frac{{d}}{{dx}}$, so $\theta$ acts on $x^m$ as multiplication by $m$. For a
polynomial $p$ and an integer $i\ge0$,
\[
\sum_{{n}} p(n)\,a(n-i)\,x^{{n}}\;=\;x^{{i}}\,\bigl(p(\theta+i)A\bigr)(x).
\]
\end{{lemma}}

\begin{{proof}}
Write $m=n-i$. Then $\sum_m p(m+i)a(m)x^{{m+i}}=x^i\sum_m p(m+i)a(m)x^m$, and $p(\theta+i)$
applied to $A=\sum_m a(m)x^m$ multiplies the $m$-th coefficient by $p(m+i)$.
\end{{proof}}

Put $b(n)=\sum_{{i=0}}^{{{r}}}p_i(n)\,a(n-i)$, the left-hand side of the conjecture, and
$B(x)=\sum_n b(n)x^n$. By Lemma~\ref{{lem:theta}},
\[
B(x)\;=\;\sum_{{i=0}}^{{{r}}}x^{{i}}\,\bigl(p_i(\theta+i)A\bigr)(x),
\]
an explicit element of the algebraic function field generated by $A$. The conjecture asserts
$b(n)=0$; so it holds for all $n$ exactly when $B=0$, and for all $n>d$ exactly when $B$ is a
polynomial of degree $d$. Both are decided symbolically, with no truncation and no numerics.

\section{{The theorem}}

\begin{{theorem}}
\[
{rec}\;=\;0
\]
{thm}
\end{{theorem}}

\begin{{proof}}
$B$ was formed as above and simplified in the function field. {concl} Since $A$ reproduces the
entry's published terms, $b$ is the sequence the entry's conjecture is about, and the statement
follows.
\end{{proof}}

\section{{Verification}}

First, the generating function reproduces all ${h['nterms']}$ published terms exactly. Second,
the conjectured recurrence was evaluated directly on those terms, with no generating function
involved, and holds wherever the proved range and the data overlap. Third, the residual $B$ was
computed symbolically rather than from a truncated series, and its series expansion was taken
independently to confirm the coefficients it predicts.

\begin{{thebibliography}}{{9}}
\bibitem{{oeis}} The OEIS Foundation, \emph{{The On-Line Encyclopedia of Integer Sequences}},
\url{{https://oeis.org}}, 2026. Sequence {a}.
\bibitem{{stanley2}} R.~P.~Stanley, \emph{{Enumerative Combinatorics}}, Volume 2, Cambridge
University Press, 1999. (Algebraic and D-finite generating functions.)
\bibitem{{kp}} M.~Kauers and P.~Paule, \emph{{The Concrete Tetrahedron}}, Springer, 2011.
\end{{thebibliography}}

\end{{document}}
"""
